sonar.projectKey=SEP2_week3
sonar.projectName=SEP2 week3
sonar.projectVersion=1.0
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xm
sonar.sources=src/main/java
sonar.tests=src/test/java